/*import { useEffect, useState } from "react";
import Board from "../Board/Board";
import handleMemoClick from "../components/memoClick";

const animalEmojisLevel2 = [..."🐶🐱🐭🐰🦊🦁🐯🐻🐨🐼🦓🐴🦄🐮🐷🐸🐔🐦🐧🐢"];

export const metadata = {
  title: 'Memory Game Online',
  description: 'Generated by create next app',
  developer: "Lucas Katz",
  keywords: "games - school - English - vocabulary"
}

const Animals = () => {
  const [shuffledAnimals, setShuffledAnimals] = useState([]);
  const [selectedMemoBlock, setselectedMemoBlock] = useState(null);
  const [flippedCount, setFlippedCount] = useState(0);
  const [animating, setAnimating] = useState(false);

  useEffect(() => {
    const shuffledArray = [...animalEmojisLevel2, ...animalEmojisLevel2];
    for (let i = shuffledArray.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    const formattedArray = shuffledArray.map((emoji, i) => ({ index: i, emoji, flipped: false }));
    setShuffledAnimals(formattedArray);
  }, []);

  const handleClick = (memoBlock) => {
    if (flippedCount === 2) {
      return;
    }

    handleMemoClick(
      memoBlock,
      shuffledAnimals,
      setShuffledAnimals,
      selectedMemoBlock,
      setselectedMemoBlock,
      flippedCount,
      setFlippedCount,
      animating,
      setAnimating
    );
  };

  return (
    <Board memoryCard={shuffledAnimals} handleClick={handleClick} />
  );
}

export default Animals;
*/
