import { useEffect, useState } from "react";
import Board2 from "../Board/Board2"; 
import handleMemoClick2 from "../components/memoClick2";

const animalEmojis = [
  { emoji: "🐶", id: 1 },
  { emoji: "🐱", id: 2 },
  { emoji: "🐭", id: 3 },
  { emoji: "🐰", id: 4 },
  { emoji: "🦊", id: 5 },
  { emoji: "🦁", id: 6 },
  { emoji: "🐯", id: 7 },
  { emoji: "🐻", id: 8 },
  { emoji: "🐨", id: 9 },
  { emoji: "🐼", id: 10 },
  { emoji: "🦓", id: 11 },
  { emoji: "🐴", id: 12 },
  { emoji: "🦄", id: 13 },
  { emoji: "🐮", id: 14 },
  { emoji: "🐷", id: 15 },
  { emoji: "🐸", id: 16 },
  { emoji: "🐔", id: 17 },
  { emoji: "🐦", id: 18 },
  { emoji: "🐧", id: 19 },
  { emoji: "🐢", id: 20 },
  { emoji: "turtle", id: 20 },
  { emoji: "dog", id: 1 },
  { emoji: "cat", id: 2 },
  { emoji: "mouse", id: 3 },
  { emoji: "rabbit", id: 4 },
  { emoji: "fox", id: 5 },
  { emoji: "lion", id: 6 },
  { emoji: "tiger", id: 7 },
  { emoji: "bear", id: 8 },
  { emoji: "koala", id: 9 },
  { emoji: "panda", id: 10 },
  { emoji: "zebra", id: 11 },
  { emoji: "horse", id: 12 },
  { emoji: "unicorn", id: 13 },
  { emoji: "cow", id: 14 },
  { emoji: "pig", id: 15 },
  { emoji: "frog", id: 16 },
  { emoji: "chicken", id: 17 },
  { emoji: "bird", id: 18 },
  { emoji: "penguin", id: 19 },
];

const animalEmojisLevel2 = [
  { emoji: "🐶", id: 1 },
  { emoji: "🐱", id: 2 },
  { emoji: "🐭", id: 3 },
  { emoji: "🐰", id: 4 },
  { emoji: "🦊", id: 5 },
  { emoji: "🦁", id: 6 },
  { emoji: "🐯", id: 7 },
  { emoji: "🐻", id: 8 },
  { emoji: "🐨", id: 9 },
  { emoji: "🐼", id: 10 },
  { emoji: "🦓", id: 11 },
  { emoji: "🐴", id: 12 },
  { emoji: "🦄", id: 13 },
  { emoji: "🐮", id: 14 },
  { emoji: "🐷", id: 15 },
  { emoji: "🐸", id: 16 },
  { emoji: "🐔", id: 17 },
  { emoji: "🐦", id: 18 },
  { emoji: "🐧", id: 19 },
  { emoji: "🐢", id: 20 },
];

export const metadata = {
  title: 'Memory Game Online',
  description: 'Generated by create next app',
  developer: "Lucas Katz",
  keywords: "games - school - English - vocabulary"
}

const Animals2 = () => {
  const [shuffledAnimals, setShuffledAnimals] = useState([]);
  const [selectedMemoBlock, setselectedMemoBlock] = useState(null);
  const [animating, setAnimating] = useState(0); 
  const [comparing, setComparing] = useState(false); 
  const [selectedLevel, setSelectedLevel] = useState(3);

  useEffect(() => {
    let selectedArray;
    switch (selectedLevel) {
      case 1:
        // Reduce el array a la mitad y luego lo duplica para el nivel 1
        selectedArray = animalEmojisLevel2.slice(0, animalEmojisLevel2.length / 2)
                          .concat(animalEmojisLevel2.slice(0, animalEmojisLevel2.length / 2)); 
        break;
      case 2:
        selectedArray = animalEmojisLevel2.concat(animalEmojisLevel2)
        break;
      case 3:
      default:
        selectedArray = animalEmojis; // Usa el array original para el nivel 3 o por defecto
        break;
    }

    const shuffledArray = [...selectedArray];
    for (let i = shuffledArray.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    const formattedArray = shuffledArray.map((item, i) => ({ index: i, ...item, flipped: false }));
    setShuffledAnimals(formattedArray);
  }, [selectedLevel]);

  const handleClick = (memoBlock) => {
    if (comparing) {
      return;
    }

    if (animating < 2) {
      handleMemoClick2(
        memoBlock,
        shuffledAnimals,
        setShuffledAnimals,
        selectedMemoBlock,
        setselectedMemoBlock,
        animating,
        setAnimating,
        comparing,
        setComparing,
        animalEmojis
      );
    }
  };

  return (
    <Board2 memoryCard={shuffledAnimals} handleClick={handleClick} />
  );
}

export default Animals2;

