import { useEffect, useState } from "react";
import Board from "../Board/Board";
import handleMemoClick from "../components/memoClick";
const foodEmojis = [..."🍔🍕🌭🍟🥪🌮🥙🥗🥘🍝🍜🍲🍛🍣🍤🍱🍚🍨🍦🍰"];

export const metadata = {
  title: 'Memory Game Online',
  description: 'Generated by create next app',
  developer: "Lucas Katz",
  keywords: "games - school - English - vocabulary"
}

const Food = () => {
  const [shuffledfood, setShuffledfood] = useState([]);
  const [selectedMemoBlock, setselectedMemoBlock] = useState(null);
  const [animating, setAnimating] = useState(0); // Nuevo estado para contar las tarjetas animando
  const [comparing, setComparing] = useState(false); // Estado para indicar si se está comparando

  useEffect(() => {
    const shuffledArray = [...foodEmojis, ...foodEmojis];
    for (let i = shuffledArray.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    const formattedArray = shuffledArray.map((emoji, i) => ({ index: i, emoji, flipped: false }));
    setShuffledfood(formattedArray);
  }, []);

  const handleClick = (memoBlock) => {

    if (comparing) {
      return;
    }

    if (animating < 2) {
      handleMemoClick(
        memoBlock,
        shuffledfood,
        setShuffledfood,
        selectedMemoBlock,
        setselectedMemoBlock,
        animating,
        setAnimating, 
        comparing,
        setComparing 
      );
    }
  };

  return (
    <Board memoryCard={shuffledfood} handleClick={handleClick} />
  );
}

export default Food;