import { useEffect, useState } from "react";
import Board2 from "../Board/Board2"; 
import handleMemoClick2 from "../components/memoClick2";
import { animalEmojis, animalEmojisLevel2 } from "../Data/data";

export const metadata = {
  title: 'Memory Game Online',
  description: 'Generated by create next app',
  developer: "Lucas Katz",
  keywords: "games - school - English - vocabulary"
}

const MemoryLogic = ({ selectedLevel, onCounterIncrement }) => {
  const [shuffledAnimals, setShuffledAnimals] = useState([]);
  const [selectedMemoBlock, setselectedMemoBlock] = useState(null);
  const [animating, setAnimating] = useState(0); 
  const [comparing, setComparing] = useState(false); 

 


  const resetBoard = () => {
    let selectedArray;
    switch (selectedLevel) {
      case 1:
        selectedArray = animalEmojisLevel2
          .slice(0, animalEmojisLevel2.length / 2)
          .concat(animalEmojisLevel2.slice(0, animalEmojisLevel2.length / 2));
        break;
      case 2:
        selectedArray = animalEmojisLevel2.concat(animalEmojisLevel2);
        break;
      case 3:
      default:
        selectedArray = animalEmojis;
        break;
    }

    const shuffledArray = [...selectedArray];
    for (let i = shuffledArray.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    const formattedArray = shuffledArray.map((item, i) => ({ index: i, ...item, flipped: false }));
    setShuffledAnimals(formattedArray);

    // Restablecer otros estados si es necesario
    setselectedMemoBlock(null);
    setAnimating(0);
    setComparing(false);
  };

  useEffect(() => {
    let selectedArray;
    switch (selectedLevel) {
      case 1:
        selectedArray = animalEmojisLevel2.slice(0, animalEmojisLevel2.length / 2)
          .concat(animalEmojisLevel2.slice(0, animalEmojisLevel2.length / 2)); 
        break;
      case 2:
        selectedArray = animalEmojisLevel2.concat(animalEmojisLevel2)
        break;
      case 3:
      default:
        selectedArray = animalEmojis;
        break;
    }

    const shuffledArray = [...selectedArray];
    for (let i = shuffledArray.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    const formattedArray = shuffledArray.map((item, i) => ({ index: i, ...item, flipped: false }));
    setShuffledAnimals(formattedArray);
  }, [selectedLevel]);

  const handleClick = (memoBlock) => {
    if (comparing) {
      
      return;
    }

    if (animating < 2) {
 
      handleMemoClick2(
        memoBlock,
        shuffledAnimals,
        setShuffledAnimals,
        selectedMemoBlock,
        setselectedMemoBlock,
        animating,
        setAnimating,
        comparing,
        setComparing,
        animalEmojis
        
      );
      if(animating===1){
        
      onCounterIncrement();}
    }
  };
  

  return (
    <>
    <Board2 memoryCard={shuffledAnimals} handleClick={handleClick} resetBoard={resetBoard} />
    </>
  );
}

export default MemoryLogic;


